macro_rules! assemble_icon_set {
    (
        $sidebar:ident,
        $topbar:ident,
        $views:ident,
        $toolbar:ident,
        $card:ident,
        $block_menu:ident,
        $property:ident,
        $quick_find:ident,
        $page_link_picker_random:ident,
        $page_link_picker_categories:ident,
        $theme:ident,
    ) => {
        Self {
            sidebar: $sidebar,
            topbar_menu: $topbar.topbar_menu,
            topbar_share: $topbar.topbar_share,
            topbar_share_chevron: $topbar.topbar_share_chevron,
            topbar_lock: $topbar.topbar_lock,
            topbar_chip_chevron: $topbar.topbar_chip_chevron,
            topbar_favorite_inactive: $topbar.topbar_favorite_inactive,
            topbar_favorite_active: $topbar.topbar_favorite_active,
            topbar_actions: $topbar.topbar_actions,
            topbar_copy_link: $topbar.topbar_copy_link,
            view_table_active: $views.view_table_active,
            view_table_inactive: $views.view_table_inactive,
            view_board_inactive: $views.view_board_inactive,
            view_board_active: $views.view_board_active,
            view_list_active: $views.view_list_active,
            view_list_inactive: $views.view_list_inactive,
            view_gallery_active: $views.view_gallery_active,
            view_gallery_inactive: $views.view_gallery_inactive,
            view_calendar_active: $views.view_calendar_active,
            view_calendar_inactive: $views.view_calendar_inactive,
            view_timeline_active: $views.view_timeline_active,
            view_timeline_inactive: $views.view_timeline_inactive,
            calendar_chevron_left: $views.calendar_chevron_left,
            calendar_chevron_right: $views.calendar_chevron_right,
            toolbar_minimize: $toolbar.toolbar_minimize,
            toolbar_restore: $toolbar.toolbar_restore,
            toolbar_filter: $toolbar.toolbar_filter,
            toolbar_sort: $toolbar.toolbar_sort,
            toolbar_lightning: $toolbar.toolbar_lightning,
            toolbar_magic_wand: $toolbar.toolbar_magic_wand,
            ai_autofill_magic_wand: $toolbar.ai_autofill_magic_wand,
            ai_autofill_external_link: $toolbar.ai_autofill_external_link,
            ai_autofill_plus: $toolbar.ai_autofill_plus,
            ai_autofill_chevron: $toolbar.ai_autofill_chevron,
            toolbar_search: $toolbar.toolbar_search,
            toolbar_expand: $toolbar.toolbar_expand,
            toolbar_settings: $toolbar.toolbar_settings,
            new_button_chevron: $toolbar.new_button_chevron,
            card_action_edit: $card.card_action_edit,
            card_action_ellipsis: $card.card_action_ellipsis,
            close: $card.close,
            page: $card.page,
            page_link_picker_random: $page_link_picker_random,
            page_link_picker_categories: $page_link_picker_categories,
            page_toggle_collapsed: $card.page_toggle_collapsed,
            page_toggle_collapsed_colors: $card.page_toggle_collapsed_colors,
            page_toggle_expanded_colors: $card.page_toggle_expanded_colors,
            page_checkbox_checked: $card.page_checkbox_checked,
            page_block_add: $block_menu.add,
            page_block_handle: $block_menu.handle,
            block_menu_turn_into: $block_menu.turn_into,
            block_menu_color: $block_menu.color,
            block_menu_quote_size: $block_menu.quote_size,
            block_menu_code_language: $block_menu.code_language,
            block_menu_code_wrap: $block_menu.code_wrap,
            block_menu_copy_code: $block_menu.copy_code,
            code_action_copy: $block_menu.code_action_copy,
            code_action_language_chevron: $block_menu.code_action_language_chevron,
            block_menu_copy_link: $block_menu.copy_link,
            block_menu_duplicate: $block_menu.duplicate,
            block_menu_move: $block_menu.move_to,
            block_menu_delete: $block_menu.delete,
            block_menu_comment: $block_menu.comment,
            block_menu_suggest_edits: $block_menu.suggest_edits,
            block_menu_present: $block_menu.present,
            block_menu_ask_ai: $block_menu.ask_ai,
            block_menu_skills: $block_menu.skills,
            block_menu_chevron: $block_menu.chevron,
            block_menu_checked: IconAsset::new(svg_with_paths(
                "0 0 16 16",
                &["M11.834 3.309a.625.625 0 0 1 1.072.642l-5.244 8.74a.625.625 0 0 1-1.01.085L3.155 8.699a.626.626 0 0 1 .95-.813l2.93 3.419z"],
                $theme.text_secondary,
            )),
            folder: $card.folder,
            property_status: $property.property_status,
            property_person: $property.property_person,
            property_relation: $property.property_relation,
            property_date: $property.property_date,
            property_list: $property.property_list,
            header_plus: $property.header_plus,
            quick_find_search: $quick_find.search,
            quick_find_person: $quick_find.person,
            quick_find_page: $quick_find.page,
            quick_find_database: $quick_find.database,
            quick_find_hide_highlight_pane: $quick_find.hide_highlight_pane,
            quick_find_hide_filters: $quick_find.hide_filters,
            quick_find_title_only: $quick_find.title_only,
            quick_find_title_only_active: $quick_find.title_only_active,
            quick_find_filter_chevron: $quick_find.filter_chevron,
            quick_find_add_filter: $quick_find.add_filter,
            quick_find_thumb_up: $quick_find.thumb_up,
            quick_find_thumb_down: $quick_find.thumb_down,
            quick_find_preview_link: $quick_find.preview_link,
            quick_find_preview_open: $quick_find.preview_open,
        }
    };
}

pub(super) use assemble_icon_set;
